spec:
  containers
  - name: mycontainer
    image: redis
    volumeMounts:
    - name: "secrets"
      mountPath: "/etc/my-secrets"
      readOnly: true
  volumes:
  - name: "secrets"
    secret:
      secretName: "mysecretâ€